module.exports =  {
	skillType: {// 技能中类
		'ATTACK': 1,
		'HEAL': 2,
		'REGENERATE': 3,
		'PARAM_UP': 4,
		'PARAM_DOWN': 5,
		'DEF_UP': 6,
		'POISON': 7,
		'PER_UP': 8,
		'PER_DOWN': 9,
		'PER_SUCCESS': 10
	},
	skillKind: {// 技能大类
		'ATTACK': 1,
		'SORCERY': 2,
		'RECOVERY': 3,
		'SUPPORT': 4,
		'DEFENSE': 5,
		'JAMMING': 6,
		'SPECIAL': 7
	},
	attr: {// 属性
		'FIRE': 1,
		'ICE': 2,
		'WIND': 3,
		'LIGHT': 4,
		'DARK': 5,
		'EARTH': 6,
		'THUNDER': 7,
		'WATER': 8,
		'NEUTRAL': 9,
		'FIRE_ICE': 102,
		'FIRE_WIND': 103,
		'FIRE_LIGHT': 104,
		'FIRE_DARK': 105,
		'ICE_WIND': 203,
		'ICE_LIGHT': 204,
		'ICE_DARK': 205,
		'WIND_DARK': 304,
		'WIND_LIGHT': 305,
		'LIGHT_DARK': 405
	},
	job: {
		'MERCENARY': 1,
		'MILLIONAIRE': 2,
		'THIEF': 3,
		'SINGER': 4
	},
	porm: {
		'PHYSICS': 1,
		'MAGIC': 2,
		'ALL': 3
	},
	skillTarget: {
		'SELF': 1,
		'USER_ONE': 2,
		'USER_ALL': 3,
		'ENEMY_ONE': 4,
		'ENEMY_ALL': 5,
		'DEAD_ENEMY_ONE': 6,
		'DEAD_ENEMY_ALL': 7,
		'ALL': 8
	},
	skillCond: {
		'DECK_COMBO_COUNT': 1,
		'TARGET_ATTR': 2,
		'TARGET_DEBUFF': 3,
		'RANDOM': 4,
		'SELF_OTHER_PLAY_ATTR': 5,
		'SELF_OTHER_PLAY_SKILL_KIND': 6,
		'SELF_OTHER_PLAY_RARITY': 7,
		'SELF_HP_PER': 8,
		'SELF_HP_FIXED': 9,
		'TURN': 10,
		'SELF_PLAYED_SKILL_KIND': 11,
		'FRIEND_PLAYED_SKILL_KIND': 12,
		'SELF_OTHER_PLAY_NUM': 13,
		'FRIEND_PLAY_NUM': 14,
		'TARGET_JOB_TYPE': 15,
		'SELF_PLAY_MOST_LOW_COST': 16,
		'FRIEND_PLAY_MOST_LOW_COST': 17,
		'SELF_PLAY_MOST_HIGH_COST': 18,
		'FRIEND_PLAY_MOST_HIGH_COST': 19,
		'SELF_PLAY_COST_TOTAL': 20,
		'FRIEND_PLAY_COST_TOTAL': 21,
		'SELF_DEBUFF': 22,
		'USER_SIDE_DEBUFF': 23,
		'ENEMY_SIDE_DEBUFF': 24,
		'USER_SIDE_BUFF': 25,
		'ENEMY_SIDE_BUFF': 26,
		'SELF_ENEMY_AI_FLAG': 27,
		'SELF_OTHER_PLAY_TAG': 28,
		'FRIEND_PLAY_TAG': 29,
		'SELF_PLAYED_TAG': 30,
		'FRIEND_PLAYED_TAG': 31,
		'SELF_MAIN_DECK_TAG': 32,
		'SELF_SUPPORT_DECK_TAG': 33,
		'SELF_ALL_DECK_TAG': 34,
		'SELF_MAIN_DECK_ATTR': 35,
		'SELF_MAIN_DECK_SKILL_KIND': 36,
		'SELF_BUFF': 37,
		'TARGET_BUFF': 38,
		'SELF_ENCHANT_DAMAGE': 39
	}
};